/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    CONTACT_PHONE: process.env.CONTACT_PHONE,
    CONTACT_EMAIL: process.env.CONTACT_EMAIL,
    CONTACT_ADDRESS_STREET: process.env.CONTACT_ADDRESS_STREET,
    CONTACT_ADDRESS_NUMBER: process.env.CONTACT_ADDRESS_NUMBER,
    CONTACT_ADDRESS_CITY: process.env.CONTACT_ADDRESS_CITY,
    CONTACT_ADDRESS_STATE: process.env.CONTACT_ADDRESS_STATE,
    CONTACT_ADDRESS_ZIP: process.env.CONTACT_ADDRESS_ZIP,
    CONTACT_ADDRESS_COUNTRY_PT: process.env.CONTACT_ADDRESS_COUNTRY_PT,
    CONTACT_ADDRESS_COUNTRY_EN: process.env.CONTACT_ADDRESS_COUNTRY_EN,
    CONTACT_ADDRESS_COUNTRY_FR: process.env.CONTACT_ADDRESS_COUNTRY_FR,
  }
}

module.exports = nextConfig
